server:
  port: 8000

jwt:
  secretKey: quanify
  expirationDateInMs: 3000000
  refreshExpirationDateInMs: 9000000

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/nctn
            token-uri: http://localhost:8080/realms/vd/protocol/openid-connect/token
#        registration:
#          client-id: nctn-app

  datasource:
    url: jdbc:postgresql://localhost:5432/nctn_db
    driver-class-name: org.postgresql.Driver
    username: nctn
    password: Crquan07!

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  main:
    allow-circular-references: true

  mvc:
    async:
      request-timeout: -1



